### ISSUE TITLE
Possible Jenkins setup

### ISSUE THREAD

**Issue by shawnkoon** [ShawnkoonZ/aws-quadtree-java#2]
Possible Jenkins setup for CI/CD

**Comment by shawnkoon** [comment]
https://aws.amazon.com/getting-started/projects/setup-jenkins-build-server/

**Comment by cwade12c** [comment]
Playing around with an EC2 Instance and Jenkins.
http://ec2-35-162-44-10.us-west-2.compute.amazonaws.com:8080

**Comment by shawnkoon** [comment]
https://wiki.jenkins-ci.org/display/JENKINS/Docker+Plugin

**Comment by cwade12c** [comment]
The Jenkins build server is complete. If we add new features to it, let's open those up as new issues.
